"""ringcentral integration and phone events

Revision ID: 17b4dfc5c81d
Revises: 9478a765c1f3
Create Date: 2026-07-07 12:15:16.872932

"""
from alembic import op
import sqlalchemy as sa


revision = '17b4dfc5c81d'
down_revision = '9478a765c1f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('rc_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('other_number', sa.String(length=24), nullable=False),
    sa.Column('other_name', sa.String(length=255), nullable=True),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=60), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('recording_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'rc_id')
    )
    op.create_index('ix_phone_events_number', 'phone_events', ['other_number'], unique=False)
    op.create_index('ix_phone_events_org_at', 'phone_events', ['org_id', 'happened_at'], unique=False)
    op.create_index(op.f('ix_phone_events_org_id'), 'phone_events', ['org_id'], unique=False)
    op.create_table('ringcentral_integration',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('jwt', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('own_numbers', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.String(length=500), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ringcentral_integration')
    op.drop_index(op.f('ix_phone_events_org_id'), table_name='phone_events')
    op.drop_index('ix_phone_events_org_at', table_name='phone_events')
    op.drop_index('ix_phone_events_number', table_name='phone_events')
    op.drop_table('phone_events')
    # ### end Alembic commands ###
