"""manual phone events carry a record link

Revision ID: 2d5215e67808
Revises: 55cc64ab0223
Create Date: 2026-07-07 16:59:20.314118

"""
from alembic import op
import sqlalchemy as sa


revision = '2d5215e67808'
down_revision = '55cc64ab0223'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_events', sa.Column('entity_type', sa.String(length=30), nullable=True))
    op.add_column('phone_events', sa.Column('entity_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_events', 'entity_id')
    op.drop_column('phone_events', 'entity_type')
    # ### end Alembic commands ###
