"""gmail sync: email tables and account cursor

Revision ID: 3b7aafe72cb9
Revises: 208bc7496447
Create Date: 2026-07-06 23:19:32.726928

"""
from alembic import op
import sqlalchemy as sa


revision = '3b7aafe72cb9'
down_revision = '208bc7496447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('gmail_id', sa.String(length=32), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=32), nullable=True),
    sa.Column('rfc_message_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('is_outgoing', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'rfc_message_id')
    )
    op.create_index(op.f('ix_email_messages_org_id'), 'email_messages', ['org_id'], unique=False)
    op.create_index('ix_email_messages_org_sent', 'email_messages', ['org_id', 'sent_at'], unique=False)
    op.create_table('email_participants',
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id', 'email')
    )
    op.create_index(op.f('ix_email_participants_email'), 'email_participants', ['email'], unique=False)
    op.add_column('google_accounts', sa.Column('gmail_history_id', sa.String(length=40), nullable=True))
    op.add_column('google_accounts', sa.Column('gmail_backfill_done', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_accounts', 'gmail_backfill_done')
    op.drop_column('google_accounts', 'gmail_history_id')
    op.drop_index(op.f('ix_email_participants_email'), table_name='email_participants')
    op.drop_table('email_participants')
    op.drop_index('ix_email_messages_org_sent', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_org_id'), table_name='email_messages')
    op.drop_table('email_messages')
    # ### end Alembic commands ###
