"""notes can link to a phone event

Revision ID: 55cc64ab0223
Revises: 17b4dfc5c81d
Create Date: 2026-07-07 13:13:46.446527

"""
from alembic import op
import sqlalchemy as sa


revision = '55cc64ab0223'
down_revision = '17b4dfc5c81d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('phone_event_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_notes_phone_event_id'), 'notes', ['phone_event_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'phone_events', ['phone_event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_phone_event_id'), table_name='notes')
    op.drop_column('notes', 'phone_event_id')
    # ### end Alembic commands ###
