"""email body cache

Revision ID: 7a2b80112c32
Revises: 3b7aafe72cb9
Create Date: 2026-07-07 09:03:16.676519

"""
from alembic import op
import sqlalchemy as sa


revision = '7a2b80112c32'
down_revision = '3b7aafe72cb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('body_text', sa.Text(), nullable=True))
    op.add_column('email_messages', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('email_messages', sa.Column('body_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'body_fetched_at')
    op.drop_column('email_messages', 'body_html')
    op.drop_column('email_messages', 'body_text')
    # ### end Alembic commands ###
