"""direct interaction flag on email participants

Revision ID: 9478a765c1f3
Revises: 7a2b80112c32
Create Date: 2026-07-07 09:08:53.086334

"""
from alembic import op
import sqlalchemy as sa


revision = '9478a765c1f3'
down_revision = '7a2b80112c32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_participants', sa.Column('direct', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Reclassify existing rows: senders engaged, and recipients of the
    # mailbox owner's outgoing mail engaged.
    op.execute(
        """
        UPDATE email_participants SET direct = true
        WHERE kind = 'from'
           OR email_id IN (SELECT id FROM email_messages WHERE is_outgoing)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_participants', 'direct')
    # ### end Alembic commands ###
